### ISSUE TITLE
Drug-Reagents.dm compiling error

### ISSUE THREAD

**Issue by Asd396** [Zaers/-tg-station#105]
loading tgstation.dme
code\modules\reagents\Chemistry-Reagents\Drug-Reagents.dm:513:error: missing left-hand argument to >>.
tgstation.dmb - 1 error, 0 warnings

**Comment by optimumtact** [comment]
https://github.com/Zaers/-tg-station/commit/7b13f9851d71b7e4a72985a4655784f8b9d3f860
