### ISSUE TITLE
[Request] MoMMI Speech Module

### ISSUE THREAD

**Issue by TraitorousBastard** [Zaers/-tg-station#14]
I'd like to see a reconfiguration module similar to the Illegal Tech Module for MoMMIs that works slightly differently. What I'd like to see is this module enable speech and modify the interaction laws slightly so that speech is allowed (to prevent ValidHunt trolls from shooting any speaking MoMMI. Example :You may not interfere with any ongoing activities of another being, including notifying or hinting to the crew of illegal activities) and remove movement restrictions (AutismFort hooo)

A possible counterbalance to this would be to disable the ability for modified MoMMIs to be emagged

**Comment by octareenroon91** [comment]
The speech and z-level restrictions are each tied to a single variable in the MoMMI.  This could be pretty easily done.  I think it might work as hacking wires or a multitool option, so long as KEEPERs specifically can't alter those.

Now I want to see a way to give mommi rainbow color-cycling eyes.  This is, of course, far less important.

**Comment by octareenroon91** [comment]
See also the following discussion of the same mommi changing topic.
https://github.com/Koriath/-tg-station/issues/4

**Comment by octareenroon91** [comment]
We finally got around to this.
