### ISSUE TITLE
Virus issue

### ISSUE THREAD

**Issue by Auron1213** [Zaers/-tg-station#140]
Might be a one-off thing, haven't had time to test for replication, but
If you get genetically turned into a different entity (like human to monkey) and then back again, a virus that inhabits you is completely nullified.
This is naturally a small issue, but if you have a beneficial virus, it can become detrimental, and may show an underlying issue in Genetics and varied entities.

**Comment by Zaers** [comment]
It could be caused by the disease's `holder` not getting updated correctly when the mob transforms, that seems to kill the processing for the disease.

I'll try to find out what's breaking in this specific case
