### ISSUE TITLE
Diseases with no cure defined cure themselves instantly

### ISSUE THREAD

**Issue by Zaers** [Zaers/-tg-station#16]
bravo nolan

**Comment by Auron1213** [comment]
What the fuck am I reading?
Diseases should always have a cure.

**Comment by Zaers** [comment]
In some specific cases they have no cure set (appendicitis, corgi transformation & possibly varedited viruses)

You'd expect them to be incurable normally if there's no cure, but it just breaks and they cure themselves

**Comment by Auron1213** [comment]
Ah, ah, standard diseases. I thought you meant advanced.
