### ISSUE TITLE
Cameras are fucked

### ISSUE THREAD

**Issue by Commondragon** [Zaers/-tg-station#184]
Trying to use any camera console results in menu that only shows "cancel".  This makes remote surveillance near impossible.

**Comment by octareenroon91** [comment]
I have replicated this behavior.

**Comment by Zaers** [comment]
After some careful testing I determined the camera console works fine on byond 509.1303 but not on byond 509.1308

**Comment by octareenroon91** [comment]
I have reverted the server to use 509.1303 for now.
