### ISSUE TITLE
Dismemberment and organs rewrite 

### ISSUE THREAD

**Issue by Asd396** [Zaers/-tg-station#191]
/tg/ attempted this a short while back and the code is here: https://github.com/Ricotez/-tg-station/tree/organsystem
Maybe we should try finishing it up and porting it over? It would also allow necromorphs as an event or gamemode, for example.

**Comment by Ebinmaymayoverlord** [comment]
YES YES YES

**Comment by octareenroon91** [comment]
Sure, give it a shot.  I can announce a test server when we get to that point.

**Comment by Asd396** [comment]
Since this is definitely HAPPENING I'll close the issue for now.
