### ISSUE TITLE
APC Interaction/Bolt Issue

### ISSUE THREAD

**Issue by TraitorousBastard** [Zaers/-tg-station#2]
There's an issue when constructing APCs where they become uninteractable after being constructed. This occurs usually after the APC has been destroyed and is being rebuilt. If possible, I'd like to see the interaction issue fixed or a method introduced to cut/retract the cover lock when you cannot interact with the APC itself.

**Comment by Zaers** [comment]
It should be fixed by having them start unlocked (interface and cover) if they're being built and having a wire that toggles it, but if it isn't then I guess it must be reopened
