### ISSUE TITLE
Shuttle lighting

### ISSUE THREAD

**Issue by Commondragon** [Zaers/-tg-station#212]
I don't know how this isn't an issue yet, but seemingly at random the escape shuttle's lighting will be messed up, either on arrival to the station or when it takes off, or often both. It seems to be related to having sunglasses or similar headgear, which make the player effectively blind except for the square they're on, which increases to their immediate surroundings if they take them off. Either way, it's very inconsistent and from the fact that the squares are not darkened but straight "it's full black or its fully lit" makes it seem like its unintentional.

This can cause problems like when a traitor causes problems on the shuttle right before it takes off, and then security is suddenly blind when it takes off.

**Comment by Zaers** [comment]
It should be working properly after the very latest changes to lighting code
