### ISSUE TITLE
Filet migrawr broken

### ISSUE THREAD

**Issue by lla22** [Zaers/-tg-station#226]
Filet migrawr 5 The Manly Dorf 1 bear steak, Tools: cheap lighter

Construction Fails every-time
I have tried both with the lighter in hand and on the table, and both turned on and off.
recipe seems to be completely non-functional.

**Comment by octareenroon91** [comment]
Will investigate.

**Comment by octareenroon91** [comment]
Confirmed.  Tablecraft is strangely picky about tools.

**Comment by octareenroon91** [comment]
Changes made.  Should be craftable now, one way or another.
