### ISSUE TITLE
Food tablecraft doesn't add reagents.

### ISSUE THREAD

**Issue by octareenroon91** [Zaers/-tg-station#234]
Completing a recipe does not improve over the nutritional value of the ingredients.

**Comment by octareenroon91** [comment]
any reagents gained above and beyond that of the ingredients would be defined in bonus_reagents.
bonus_reagents is presently undefined for most foods, thanks to @Riesen's ecda8bed076131fd6fc84af7bb3d2b81de572bb0

**Comment by Koriath** [comment]
check the "table.dm" in code\modules\crafting
Pretty sure that's the proc of tablecrafting. One of them could be expanded to use reagents from the parts and put them in the final object. Could be used for this (so better veggies make better food) and for a lot of other things.

**Comment by octareenroon91** [comment]
It's not that at all.  There's two lists, ```list_reagents``` and ```bonus_reagents```.  Tablecraft uses ```bonus_reagents``` and ignores ```list_reagents```.  If you spawn a food (with a silver slime reaction or something), the game uses ```list_reagents``` only.

I see two likely solutions:
1. Fill in the missing list for every food item.
2. Add a proc to New() that copies any missing entries from one list to the other.
