### ISSUE TITLE
[Request] Add Uranium to Recycler

### ISSUE THREAD

**Issue by TraitorousBastard** [Zaers/-tg-station#24]
The upgraded recycler machine now produces extra material types after the bluespace update. The only material NOT produced is Uranium. Would it be possible to add this material to the resource output for the upgraded version of the machine?

**Comment by Zaers** [comment]
I got bad news for you, as of 647778828f8cf8fcb0a48c100f29d91732a79f2d the crusher is no longer a free material machine and will only output materials once it has accumulated enough for a sheet (this is mentioned in the changelog)

However this means it'll output uranium if there is uranium material in the items fed to it, so technically this is in
