### ISSUE TITLE
Gang territory control stuck at 0%

### ISSUE THREAD

**Issue by octareenroon91** [Zaers/-tg-station#25]
For the round ending around 2015-07-10 02:20 :

The Blasto Gang successfully performed a hostile takeover of the station!

The Psyke Gang was defeated with 0% control of the station!
[ . . . ]
The Blasto Gang was victorious with 0% control of the station!
[ . . . ]

When checking on existing gang graffiti, I noticed that the tags had gang=null , which I suspect is incorrect.

**Comment by Zaers** [comment]
Is this still an issue or did 927f55bf9c2eed48a60f02d64eeb71c002d95a14 fix it?

**Comment by octareenroon91** [comment]
I've seen nonzero gang territory more recently.

This round-end message posts on all non-gang roundtypes, though:
"The station was evacuated before a gang could claim it! The station wins!"
