### ISSUE TITLE
initial() of a list no longer generates the list, nor null!

### ISSUE THREAD

**Issue by octareenroon91** [Zaers/-tg-station#32]
Through some unclear process, losing spells down to a single one makes the mind's spell_list no longer a proper /list , and it's pretty much impossible to repair in the middle of a game.

There might be a more specific trigger, but this issue needs some attention regardless.

A shadowling player lost their spells and they could not be restored, except possibly by sending the player back to the lobby.

Further investigation suggests this is a BYOND-level issue, requiring a more realistic solution in order to adapt.

Consider the energy axe code:
attack_verb initializes like so, and stays that way because attack_verb_on is null .
attack_verb = list("attacked", "chopped", "cleaved", "torn", "cut")

https://github.com/Zaers/-tg-station/blob/master/code/game/objects/items/weapons/melee/energy.dm#L87 :
attack_verb = initial(attack_verb)

After this line, attack_verb becomes something other than null or a list.  No attack with the axe can even complete, it's a brick after you turn it off for the first time.

There may be other points where this problem comes in, but these two I can confirm.

**Comment by Zaers** [comment]
t-t-thanks BYOND, according to varedit it somehow turns into a file

I guess I'll make a var to store the initial list and use it to bypass initial() as a hack

**Comment by Zaers** [comment]
>http://www.byond.com/forum/?post=1891233
>not a bug

I wonder who could be behind this

**Comment by octareenroon91** [comment]
It's not even null.  If it were null, I could varedit affected vars into /lists again.

Also, at least one of the problems I found involved an on/off toggle.  Vars named thing, thing_on, and thing_off are likely to suit our purposes more anyways.

Impressive breaking change, though.  bravo byond.

**Comment by octareenroon91** [comment]
code/game/pooling/pool.dm -- this garbage collector uses initial() on lists.  This new change bricks the gc!

```
/datum/proc/ResetVars()
        var/list/excluded = list("animate_movement", "contents", "loc", "locs", "parent_type", "vars", "verbs", "type")

        for(var/V in vars)
                if(V in excluded)
                        continue

                vars[V] = initial(vars[V])

/atom/movable/ResetVars()
        ..()
        loc = null
        contents = initial(contents) //something is really wrong if this object still has stuff in it by this point
```

**Comment by octareenroon91** [comment]
https://github.com/Zaers/-tg-station/pull/37

**Comment by octareenroon91** [comment]
Null isn't regarded as an empty list, so the varedit tool should probably gain a [NEW EMPTY LIST] option.
