### ISSUE TITLE
Possible crash cause

### ISSUE THREAD

**Issue by TraitorousBastard** [Zaers/-tg-station#5]
Right before the latest server hang I was placing an APC in an area where one might not be covered by the standard mapping. I don't know if this is the cause of the issue, but since APCs were recently modified I thought it might be worth mentioning.

**Comment by Zaers** [comment]
Was it in the mining asteroid?

**Comment by TraitorousBastard** [comment]
Yes, near the research outpost

**Comment by Zaers** [comment]
Ah, I think I know why it hanged then, I'll work on a fix

**Comment by TraitorousBastard** [comment]
Unrelated question, is anyone working on resetting the server?

**Comment by Zaers** [comment]
I don't think so

**Comment by Zaers** [comment]
This should fix the issue, seems it was caused by the areas being huge
If it doesn't properly resolve it, it'll need to be reopened
