### ISSUE TITLE
Hooch vs Napalm

### ISSUE THREAD

**Issue by octareenroon91** [Zaers/-tg-station#60]
The recipes for these two call for fuel, ethanol, and sugar, though in different ratios.

One of these recipes should probably be changed.

**Comment by phil235** [comment]
Fixed on the tgstation branch (https://github.com/tgstation/-tg-station/pull/9199/files#diff-46961b0bf4e70f55a1d3e4c341b072b7R209) , we changed Hooch recipe to use ethanol, fuel and enzymes as catalyst.

**Comment by octareenroon91** [comment]
Thanks.
