### ISSUE TITLE
[Idea] Station power management

### ISSUE THREAD

**Issue by Asd396** [Zaers/-tg-station#70]
Power sub-stations! We already have something like this in smaller scale with the gravity and tcomms SMES-cells. What if each section of the station would, by default, be connected straight to the grid at a single location. At each of these locations, power sub-stations, there would be a SMES-cell disconnected by default. If engineering wishes to utilize them, they'll just need to wire these cells to the grid, giving plenty of back-up power to each section of the station and a robust way to control the power of the station. I think Bay has something like this, in addition to a central computer in engineering that can configure the SMES-cells connected to the grid.

**Comment by Asd396** [comment]
Now implemented. The only things left are bridge and engineering sub-stations, along with possibly minisat.

**Comment by Koriath** [comment]
Engineering might not need it. The whole place is pretty much a giant substation after all.
Bridge and minisat could do with one. Making up room for them might be harder though.

**Comment by Asd396** [comment]
Oh, and another thing: sub-grids could really use another wire color so engineers can right away see what they're dealing with when fixing wires. Green?

**Comment by Asd396** [comment]
Fully implemented
