### ISSUE TITLE
Tweak ID access to Ore Redemption Machine

### ISSUE THREAD

**Issue by claniraq** [Zaers/-tg-station#84]
Only cargo staff should have the required access to unload sheets from ORMs. This ensures that the Cargo Bay and Quartermaster perform proper logistics instead of having a Danielhen/Kyres/Puppysky emulator siphoning every resource. It would be in the cargo's staff best interests that everyone got the resources that they needed instead of whoever came first.

It would make wall mounted request consoles actually useful and would force player interaction and cooperation instead of the autism and greed festival that it currently is.

**Comment by Koriath** [comment]
We will try this since the ORM got moved further inside cargo.
But this might cause problems.
In any case, scientists can mine on their own, without the ORM (they can make a second one).

**Comment by Koriath** [comment]
Wait, I'm not sure what you mean by this.
I just checked the code, noone has acess to the ORM except for cargo personnel.

There's two diferent acesses: "access_mining_station" and "access_mineral_storeroom".
It seems that to redeem points, you need the first, but to remove sheets, you just need the second.
Should I just remove the second acess from Scientists and the like?

**Comment by claniraq** [comment]
@Koriath 
Mineral store room (Area covers 6 tiles in R&D) access is what determines if you can unload sheets.

In theory you'd have cargo staff interacting with other departments, responding to request consoles and sending resources using the mailroom instead of the ORM being "first come/first serve".

>Should I just remove the second acess from Scientists and the like?
Yes. Chemists (CMO?) and Research staff have that access in their ID card.

>In any case, scientists can mine on their own, without the ORM
This is usually the case.
