### ISSUE TITLE
Relocate Ore Redemption Machine.

### ISSUE THREAD

**Issue by claniraq** [Zaers/-tg-station#85]
The current location (Port hallway) makes it extremely easy for someone to steal cargo personnel's ID, deconstruct the machine to illegally obtain resources, outright grab stacks of sheets while someone is unloading them or to have a really autistic "person" (A scientist) hoard all the sheets without considering what everyone else needs.

Move it inside the cargo bay (Two or three tiles Above the mailroom's fore wall should be fine) to allow cargo staff to determine who needs what using both logic and the requests consoles while making it challenging for whoever wants the resources illegitimately as they now have to infiltrate the cargo bay instead of just running through the hall with a screwdriver and crowbar.

**Comment by Koriath** [comment]
Moved it to the Mining are of cargo. Miners can dump ore north of it, retrieve the points and spend it without leaving that area if they so wish.
New sheets are dropped one tile east of the conveyr belt to facilitate plasma sheets being sent to centcomm if there's no need of more plasma aboard the station.
