### ISSUE TITLE
Reduce the amount of cable lines to a department to 1.

### ISSUE THREAD

**Issue by claniraq** [Zaers/-tg-station#86]
Every department's power net has 3-4 wires, one generally leading into a hallway and all spare ones leading into maintenance.

It's extremely difficult to sabotage a department's power supply as you have to go through all 4 wires. Coincidentally, it's time consuming to set up a department specific SMES unit as you have to, again, get rid of the extra power lines.

**Comment by Koriath** [comment]
It's gonna be fixed and centralized to one wire leading to a department's SMES and then that SMES wired to the grid.

**Comment by Asd396** [comment]
Been done for a while
