### ISSUE TITLE
Atmospherics' Gas miners

### ISSUE THREAD

**Issue by claniraq** [Zaers/-tg-station#88]
They're easier to carry than emaciated African children, can permanently fuck up a room, they barely consume any energy and all you need to move them is a space suit and a wrench. 

Did I mention these devices are stored in a place guarded by a security camera (That isn't even motion sensitive), in a room made out of reinforced walls, with a man sized reinforced window that can be easily destroyed?

Those "design flaws" are left overs from an era where those rooms only had a canister. An easy fix would've been upgrading the cameras to being motion sensitive and replacing the window that's meant to enable observation with a reinforced wall (you've got the camera anyways). Another suggestion is increasing their power consumption as even a portable scrubber takes more power from a room's APC than a gas miner.

**Comment by Koriath** [comment]
They have been secured.

**Comment by octareenroon91** [comment]
Please confirm if this issue is ready to be closed.

**Comment by octareenroon91** [comment]
The miners are fully surrounded by R-Walls at present.
