### ISSUE TITLE
Several Compilation Errors on Cart.dm and the PDA Cart Additions

### ISSUE THREAD

**Issue by gitgud-software** [Zaers/-tg-station#89]
Output:
loading tgstation.dme
loading interface/skin.dmf
code/game/machinery/computer/buildandrepair.dm:252:error: /obj/machinery/computer/rcon: undefined type path
code/game/objects/items/devices/PDA/cart.dm:836:error: BR: undefined type: BR
code/game/objects/items/devices/PDA/cart.dm:837:error: BR.RCon_tag: undefined type: BR.RCon_tag
code/game/objects/items/devices/PDA/cart.dm:837:error: BR.RCon_tag: undefined type: BR.RCon_tag
code/game/objects/items/devices/PDA/cart.dm:839:error: BR.RCon_tag: undefined type: BR.RCon_tag
code/game/objects/items/devices/PDA/cart.dm:840:error: BR.on: undefined type: BR.on
code/game/objects/items/devices/PDA/cart.dm:836: warning : BR: variable defined but not used
tgstation.dmb - 6 errors, 1 warning (9/13/15 11:30 pm)

**Comment by Asd396** [comment]
-tg-station-master is compiling fine for me with these additions. Are "code/game/machinery/computer/RCON_console.dm" and "code/modules/power/breaker_box.dm" #included in tgstation.dme?

**Comment by Koriath** [comment]
That was me. I uploaded a dme that didn't had that line. Sorry about that. I'm starting to use the command line to solve file conflicts, and I guess I fucked up.
