### ISSUE TITLE
Please check the logs around 2015-09-14 04:00

### ISSUE THREAD

**Issue by octareenroon91** [Zaers/-tg-station#93]
This round, first after the updates and restart, showed multiple lock-ups of the master controller.

Warning. The Master Controller has not fired in the last 400 ticks. Automatic restart in 100 ticks.
Warning. The Master Controller has still not fired within the last 500 ticks. Killing and restarting...

**Comment by Koriath** [comment]
I'm not sure what sort of log I'm suposed to get.
The one's the server prints to me don't have anything like that at that time.

**Comment by octareenroon91** [comment]
Aw, heck.  Maybe just keep an eye out for it in-game, since it happened repeatedly in one round.

I don't know how hatestation is setup to save the runtime or stderror log.

**Comment by Koriath** [comment]
If there's a place where I can see the runtime errors, I'd very much like to know it.
As far as I can tell, I can download an atack log, or a complete server log.
Neither show runtime errors.

**Comment by octareenroon91** [comment]
I guess these are lost.
