### ISSUE TITLE
Add gas pumps to emergency storages

### ISSUE THREAD

**Issue by claniraq** [Zaers/-tg-station#94]
This simple change will allow everyone to refill canisters, as well as enabling exosuits to connect to the ports to refill their air supply after their canister gets damaged.

**Comment by Koriath** [comment]
There were already a bunch of ports with an air canister on most emergency storages. I'll see about adding more if those are not enough.
There's one above the casino for instance.

**Comment by claniraq** [comment]
I meant gas pumps inside each emergency storage to actually refill canisters using the distro pipe net.

Air pumps in the locker room and in the starboard primary hallway allow you to replenish air tanks, but each canister in every emergency storage is a one use object unless you're willing to haul them to atmospherics.

**Comment by Asd396** [comment]
Oh, you mean refill at an arbitrary pressure instead of the distro pipeline pressure?

**Comment by Koriath** [comment]
The way you refil canisters right now is that you stick an air canister in Emergency storage on top of the air port, wrench it, then plug wathever tank you want to refil to the canister.
It's pretty much like engies charging plasma canisters for the rad collectors, except you have the air canister connected to the distro loop.

**Comment by Asd396** [comment]
This refills canisters at distribution pressure, which is ~100 kPa by default

**Comment by octareenroon91** [comment]
Please confirm if this issue is ready to be closed.

**Comment by Asd396** [comment]
Go ahead
