### ISSUE TITLE
malfunction.dm and spirit.dm compiling errors

### ISSUE THREAD

**Issue by Asd396** [Zaers/-tg-station#96]
code\modules\mob\living\simple_animal\spirit.dm:431:error: appearance: undefined var
code\game\gamemodes\malfunction\malfunction.dm:216:error:= : bad text
code\modules\mob\living\simple_animal\spirit.dm:431:error: A.appearance: undefined var
tgstation.dmb - 3 errors, 0 warnings

**Comment by Koriath** [comment]
I think that for now, we just ignore the spirite.dm.
I'll submit a fix so it stops bothering us.
